name: ruff

on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format
      - name: Commit changes
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply automatic formatting changes" || true
          git push