name: latex
on:
  push:
    tags: ["docs"]
  pull_request:
    branches: [main]
jobs:
  build_latex:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Give compile.sh execute permissions.
        run: chmod +x docs/compile.sh
      - name: List files in directory
        run: ls docs/Development_Guide/
      - name: Compile LaTeX document (English)
        uses: xu-cheng/texlive-action@v2
        with:
          texlive_version: 2024
          run: |
            ./docs/compile.sh en
      - name: Upload english PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Development_Guide.pdf
          path: docs/Development_Guide.pdf
      - name: Upload PDF Files to Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "docs/Development_Guide.pdf"
          tags: false
          overwrite: true
          draft: true
          update_latest_release: true
