name: latex
on:
  push:
    tags: ["docs"]
  pull_request:
    branches: [main]
jobs:
  build_latex:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Ensure we're on a branch
        shell: bash
        run: |
          if [ -n "$GITHUB_HEAD_REF" ]; then
            SAFE_BRANCH=$(echo "$GITHUB_HEAD_REF" | tr -cd '[:alnum:]-_.')
            echo "Sanitized branch name: $SAFE_BRANCH"
            git checkout -B "$SAFE_BRANCH"
          else
            BRANCH="${GITHUB_REF##refs/heads/}"
            echo "Using branch from GITHUB_REF: $BRANCH"
            git checkout "$BRANCH"
          fi
      - name: Give compile.sh execute permissions.
        run: chmod +x docs/compile.sh
      - name: Compile LaTeX document (English)
        uses: xu-cheng/texlive-action@v2
        with:
          texlive_version: 2024
          run: |
            ./docs/compile.sh en
      - name: Upload english PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Development_Guide.pdf
          path: docs/Development_Guide.pdf
      - name: Commit PDF update to branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update Development Guide PDF"
          add: "docs/Development_Guide.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
