name: reviewdog
on: [pull_request]
jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: tsuyoshicho/action-mypy@v4
        with:
          level: warning
          setup_command:
          execute_command: |
            uv run mypy
  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-typos@v1