name: ruff

on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  lint:
    name: ruff lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
  format:
    name: ruff format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"