name: ruff

on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]

jobs:
  ruff:
    name: ruff lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check
  ruff:
    name: ruff format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff format --check